# Generated by Django 2.2.6 on 2021-01-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_like',
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='shop.Product')),
            ],
        ),
    ]
