# Generated by Django 2.2.6 on 2021-01-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bookmark_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['product']},
        ),
    ]
